### PR TITLE
Turned on CLANG modules to enable generation of DSYM files when using with Swift projects

### PR DESCRIPTION
**Pull request by Jtango18**
In order to build a Swift project with proper DSYM generation for debugging purposes and symbolication of crash reports, CLANG_ENABLE_MODULES needs to be set to YES. The other impacting change this has is that users of the framework will need to import Webkit.Framework manually. Please consider merging this change and making it part of the default framework.

### CODE REVIEW

**Comment by phvannor** [comment]
Do you consume this as a static fw, dynamic fw, or cocoapod?

**Comment by Jtango18** [comment]
Dynamic FW

On 16 Jan 2016, at 4:57 AM, Phillip Van Nortwick <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you consume this as a static fw, dynamic fw, or cocoapod?

-

**Comment by phvannor** [comment]
:+1: I'm ok with taking this.  Working on verifying how the new step (require webkit) will impact doc/etc.  Once we have signoff that will be taken care of will merge this one in.

**Comment by Jtango18** [comment]
Hold fire on merging this one Phil. I've just noticed it's still throwing up a lot of compiler warnings which I'd like to get resolved first.

**Pull request closed without merging**
