### PR TITLE
Increase timeout for a few offline unit tests to let build pass

### PR DESCRIPTION
**Pull request by dhei**

### CODE REVIEW

**Comment by dhei** [comment]
@shrishrirang: I intend to increase timeout to fix the test of timeout issues. I ran the travis-ci a couple of times but with no luck, still getting same timeout issues on Mac. So I will leave it to you to further investigate the root cause of the problem.

**Comment by damienpontifex** [comment]
@dhei @shrishrirang I have also looked into this and I don't believe it is the timeout that is the issue. It may be something to do with a deadlock waiting on the run loop. 

I had some success changing the waiter to use `dispatch_group`, but haven't had complete success.

**Comment by shrishrirang** [comment]
Sure, I’ll take a look when I’m back to office next week. Thanks!

**Comment by dhei** [comment]
Close as this PR is obviously not the right fix.

**Pull request closed without merging**
