### PR TITLE
Library components and mac distribution

### PR DESCRIPTION
**Pull request by damienpontifex**
A first look at what a solution to #43 and/or #33 would look like. Would be interested on discussion, feedback and design considerations

Focus was to take some of the separate features of the library and define these components as separate [cocoapod subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec). This could be taken further, with other features like offline, but begins with specs of

- MicrosoftAzureMobile/Core
- MicrosoftAzureMobile/Login
- MicrosoftAzureMobile/Push

Key feature would be to allow developers to only include the components of the library they need. The default install for the pod would remain as before (installing all of these subspecs and hence the complete library) avoiding breaking changes for existing developers or the quick start to include everything.

This change would also enable distribution of the Mac framework via cocoapods while limiting the install of the login subspec to iOS as there currently isn't a mac compatible implementation.

### CODE REVIEW

**Comment by paulbatum** [comment]
Hey @damienpontifex just a heads up, @shrishrirang is on vacation so it will probably be a few weeks before there is more action on this. We also have to figure out internally what infrastructure we need in order to test our OS X support, assuming we accept this PR.

**Comment by damienpontifex** [comment]
Thanks @paulbatum although this was a while ago now. Things might be a little out of date.

It was a sample to play around with how it might work. Regardless of accepting or not, interested to open up/begin the discussion.

**Comment by shrishrirang** [comment]
Hey @damienpontifex, thanks for the PR! Sorry to get back to you so late on this.

Overall, this seems like a good approach to sharing code between the two targets (iOS and OS X). After discussing in the team today we decided to park the changes for now. We will take up these changes when we plan to implement the login UI for OS X. We will continue to use  https://github.com/Azure/azure-mobile-apps-ios-client/issues/33 to track this. This PR will be a good starting point when we get back to this!

**Comment by shrishrirang** [comment]
As mentioned in an earlier comment, this will be taken up later.

**Pull request closed without merging**
